name: Web Build Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  web-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Export Expo web build
        run: npx expo export --platform web
        env:
          EXPO_USE_STATIC: "1"

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/